import { useDates } from '../../shared/helpers/useDate'
import type { DbSchema } from './types'

const { getToday } = useDates()

const defaultData: DbSchema = {
  user: {
    balance: 2832,
    level: 23,
    exp_current: 475,
    exp_needed: 1039,
    focused_time: 1874,
    pomodoros: 16,
    questlines_done: 1,
    todos_done: 30,
    ideas_total: 13,
    habits_implemented: 8,
    exp_gained: 7579,
    crystals_gained: 1012,
    rewards_unlocked: 2,
    created_at: '2025-06-13',
  },
  questlines: [
    {
      id: 1,
      title: 'Rare Questline',
      description: 'Questlines also level depending on the time you spent on them.',
      time_spent: 1080,
      active: true,
      created_at: '2025-06-17',
      position: 0,
    },
    {
      id: 2,
      title: 'Use Timer or add manually!',
      description: 'Use or add manually.',
      time_spent: 0,
      active: false,
      created_at: '2025-06-17',
      position: 1,
    },
  ],
  quests: [
    {
      id: 1,
      title: 'Sub-quests',
      time_spent: 1080,
      questline_id: 1,
      tag_name: 'Rare',
      position: 0,
    },
    {
      id: 2,
      title: 'Reward Calc',
      time_spent: 0,
      questline_id: 1,
      tag_name: 'Rare',
      position: 1,
    },
    {
      id: 3,
      title: 'TODO',
      time_spent: 0,
      questline_id: 1,
      tag_name: 'Legendary',
      position: 2,
    },
  ],
  tasks: [
    {
      id: 1,
      title: 'Bundle your',
      quest_id: 1,
      completed: true,
      position: 0,
    },
    {
      id: 2,
      title: "TODO's",
      quest_id: 1,
      completed: true,
      position: 1,
    },
    {
      id: 3,
      title: 'in subtasks',
      quest_id: 1,
      completed: true,
      position: 2,
    },
    {
      id: 4,
      title: 'Claim Rewards',
      quest_id: 1,
      completed: true,
      position: 3,
    },
    {
      id: 5,
      title: 'When DONE!',
      quest_id: 1,
      completed: true,
      position: 4,
    },
    {
      id: 6,
      title: '->',
      quest_id: 1,
      completed: true,
      position: 5,
    },
    {
      id: 7,
      title: 'Rewards get',
      quest_id: 2,
      completed: false,
      position: 0,
    },
    {
      id: 8,
      title: 'Calculated',
      quest_id: 2,
      completed: false,
      position: 1,
    },
    {
      id: 9,
      title: 'Dynamically',
      quest_id: 2,
      completed: false,
      position: 2,
    },
    {
      id: 10,
      title: '+ Global EXP',
      quest_id: 2,
      completed: false,
      position: 3,
    },
    {
      id: 11,
      title: '+ Tag EXP',
      quest_id: 2,
      completed: false,
      position: 4,
    },
    {
      id: 12,
      title: '+ Crystals',
      quest_id: 2,
      completed: false,
      position: 5,
    },
    {
      id: 13,
      title: 'Based on ',
      quest_id: 2,
      completed: false,
      position: 6,
    },
    {
      id: 14,
      title: 'Time Spent',
      quest_id: 2,
      completed: false,
      position: 7,
    },
    {
      id: 15,
      title: 'Using Timer',
      quest_id: 2,
      completed: false,
      position: 8,
    },
    {
      id: 16,
      title: 'And Amount',
      quest_id: 2,
      completed: false,
      position: 9,
    },
    {
      id: 17,
      title: 'Project activation',
      quest_id: 3,
      completed: false,
      position: 0,
    },
    {
      id: 18,
      title: 'Currently only in',
      quest_id: 3,
      completed: false,
      position: 1,
    },
    {
      id: 19,
      title: 'Timer Module',
      quest_id: 3,
      completed: false,
      position: 2,
    },
  ],
  tags: [
    {
      id: 1,
      title: 'Tags Represent',
      level: 1,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 0,
    },
    {
      id: 2,
      title: 'Your Skills in',
      level: 1,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 1,
    },
    {
      id: 3,
      title: 'Real-Life',
      level: 1,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 2,
    },
    {
      id: 4,
      title: 'They Level-Up!',
      level: 1,
      exp_current: 8,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 3,
    },
    {
      id: 5,
      title: 'They can be:',
      level: 1,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 4,
    },
    {
      id: 6,
      title: 'Common',
      level: 1,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 5,
    },
    {
      id: 7,
      title: 'Uncommon',
      level: 10,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 6,
    },
    {
      id: 8,
      title: 'Rare',
      level: 25,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 7,
    },
    {
      id: 9,
      title: 'Epic',
      level: 40,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 8,
    },
    {
      id: 10,
      title: 'Legendary',
      level: 55,
      exp_current: 0,
      exp_needed: 10,
      time_spent: 0,
      created_at: '2025-06-17',
      position: 9,
    },
  ],
  ideas: [
    {
      id: 1,
      title: 'Your Backlog',
      description: 'Ideas help you giving your thoughts and inspirations a room to breath...',
      position: 0,
    },
    {
      id: 2,
      title: 'Store & Forget',
      description:
        "You can do anything but not everything. It's good having a place to store your ideas.",
      position: 1,
    },
    {
      id: 3,
      title: 'Start the project',
      description:
        'When you decide to dive into a <- project  convert your idea to a quest by clicking the bulb-icon.',
      position: 2,
    },
  ],
  habit_stacks: [
    {
      id: 1,
      title: 'Routine',
      position: 0,
    },
    {
      id: 3,
      title: 'Ranks',
      position: 1,
    },
    {
      id: 4,
      title: 'Streaks ',
      position: 2,
    },
  ],
  habits: [
    {
      id: 1,
      title: 'Habit Stacks',
      tag_name: 'Epic',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 1,
      position: 0,
      last_month_completed: [],
    },
    {
      id: 2,
      title: 'Can be ',
      tag_name: 'Legendary',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 1,
      position: 1,
      last_month_completed: [],
    },
    {
      id: 3,
      title: 'populated',
      tag_name: 'Common',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 1,
      position: 2,
      last_month_completed: [],
    },
    {
      id: 4,
      title: 'With Habits',
      tag_name: 'They Level-Up!',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 1,
      position: 3,
      last_month_completed: [],
    },
    {
      id: 5,
      title: 'Common',
      tag_name: 'Common',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 3,
      position: 0,
      last_month_completed: [],
    },
    {
      id: 6,
      title: 'Uncommon',
      tag_name: 'Uncommon',
      counter: 100,
      current_streak: 0,
      best_streak: 1,
      stack_id: 3,
      position: 1,
      last_month_completed: [],
    },
    {
      id: 7,
      title: 'Rare',
      tag_name: 'Rare',
      counter: 500,
      current_streak: 0,
      best_streak: 1,
      stack_id: 3,
      position: 2,
      last_month_completed: [],
    },
    {
      id: 8,
      title: 'Epic',
      tag_name: 'Epic',
      counter: 1000,
      current_streak: 0,
      best_streak: 1,
      stack_id: 3,
      position: 3,
      last_month_completed: [],
    },
    {
      id: 9,
      title: 'Legendary',
      tag_name: 'Legendary',
      counter: 2000,
      current_streak: 0,
      best_streak: 1,
      stack_id: 3,
      position: 4,
      last_month_completed: [],
    },
    {
      id: 10,
      title: 'They track',
      tag_name: 'Common',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 0,
      last_month_completed: [],
    },
    {
      id: 11,
      title: 'Your Streaks',
      tag_name: 'Common',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 1,
      last_month_completed: [],
    },
    {
      id: 12,
      title: 'Counters',
      tag_name: 'Uncommon',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 2,
      last_month_completed: [],
    },
    {
      id: 13,
      title: '& Records',
      tag_name: 'Legendary',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 3,
      last_month_completed: [],
    },
    {
      id: 14,
      title: 'Give EXP ',
      tag_name: 'Legendary',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 4,
      last_month_completed: [],
    },
    {
      id: 15,
      title: '& Crystals',
      tag_name: 'Legendary',
      counter: 0,
      current_streak: 0,
      best_streak: 0,
      stack_id: 4,
      position: 5,
      last_month_completed: [],
    },
  ],
  rewards: [
    {
      id: 1,
      title: 'Add Rewards',
      cost: 40,
      repeatable: true,
      position: 0,
    },
    {
      id: 2,
      title: 'To Unlock with',
      cost: 25,
      repeatable: true,
      position: 1,
    },
    {
      id: 3,
      title: 'Your Earned ',
      cost: 30,
      repeatable: true,
      position: 2,
    },
    {
      id: 4,
      title: 'Crystals 💎',
      cost: 100,
      repeatable: true,
      position: 3,
    },
    {
      id: 5,
      title: 'Can be',
      cost: 230,
      repeatable: true,
      position: 4,
    },
    {
      id: 6,
      title: 'Repeatable',
      cost: 10,
      repeatable: true,
      position: 5,
    },
    {
      id: 7,
      title: 'not Repeatable',
      cost: 20,
      repeatable: false,
      position: 6,
    },
  ],
  achievements: [],
  questlines_done: [
    {
      id: 1,
      name: 'Progress ',
      created_at: '2025-06-12',
      time_spent: 4800,
    },
  ],
}

export default defaultData
