import type { DbSchema } from './types'

const defaultData: DbSchema = {
  user: {
    balance: 180,
    level: 7,
    exp_current: 34,
    exp_needed: 120,
    focused_time: 9860,
    pomodoros: 128,
    questlines_done: 2,
    todos_done: 14,
    exp_gained: 1480,
    crystals_gained: 420,
    rewards_unlocked: 3,
    created_at: '2025-06-13',
  },
  settings: {
    timer_min: 2,
    timer_max: 120,
    timer_default_session: 25,
    currency_crysral_ratio: [1, 10],
    max_projects: 3,
  },
  years: [
    {
      year: 2025,
      time: [240, 310, 420, 390, 510, 880, 1260, 980, 720, 610, 430, 300],
    },
  ],
  questlines: [
    {
      id: 1,
      title: 'Inbox Reset',
      description: 'A tiny cleanup project for quick testing of the common rank.',
      time_spent: 45,
      active: true,
      created_at: '2026-04-01',
      position: 0,
    },
    {
      id: 2,
      title: 'UI Polish Sprint',
      description: 'A short design pass that already qualifies as uncommon.',
      time_spent: 180,
      active: false,
      created_at: '2026-04-02',
      position: 1,
    },
    {
      id: 3,
      title: 'Portfolio Case Study',
      description: 'A mid-sized project with a finished quest ready to claim.',
      time_spent: 720,
      active: false,
      created_at: '2026-04-03',
      position: 2,
    },
    {
      id: 4,
      title: 'Client Dashboard',
      description: 'An epic-sized delivery project with unfinished work.',
      time_spent: 1440,
      active: false,
      created_at: '2026-04-04',
      position: 3,
    },
    {
      id: 5,
      title: 'Knowledge Base Migration',
      description: 'A long-running legendary project with no open quests left.',
      time_spent: 2880,
      active: false,
      created_at: '2026-04-05',
      position: 4,
    },
    {
      id: 6,
      title: 'Engine Rewrite',
      description: 'A mythic-scale rewrite to showcase the top rank.',
      time_spent: 5400,
      active: false,
      created_at: '2026-04-06',
      position: 5,
    },
  ],
  quests: [
    {
      id: 1,
      title: 'Archive old notes',
      time_spent: 20,
      questline_id: 1,
      tag_id_1: 1,
      tag_id_2: 2,
      active: true,
      position: 0,
    },
    {
      id: 2,
      title: 'Write the case study',
      time_spent: 360,
      questline_id: 3,
      tag_id_1: 3,
      tag_id_2: 2,
      active: false,
      position: 0,
    },
    {
      id: 3,
      title: 'Finalize widget flows',
      time_spent: 900,
      questline_id: 4,
      tag_id_1: 4,
      tag_id_2: 5,
      active: false,
      position: 0,
    },
    {
      id: 4,
      title: 'Build migration checklist',
      time_spent: 2200,
      questline_id: 6,
      tag_id_1: 6,
      tag_id_2: 4,
      active: false,
      position: 0,
    },
  ],
  tasks: [
    {
      id: 1,
      title: 'Delete duplicate captures',
      quest_id: 1,
      completed: true,
      position: 0,
    },
    {
      id: 2,
      title: 'Rename remaining folders',
      quest_id: 1,
      completed: false,
      position: 1,
    },
    {
      id: 3,
      title: 'Collect screenshots',
      quest_id: 2,
      completed: true,
      position: 0,
    },
    {
      id: 4,
      title: 'Write first draft',
      quest_id: 2,
      completed: true,
      position: 1,
    },
    {
      id: 5,
      title: 'Map edge cases',
      quest_id: 3,
      completed: true,
      position: 0,
    },
    {
      id: 6,
      title: 'Implement loading states',
      quest_id: 3,
      completed: false,
      position: 1,
    },
    {
      id: 7,
      title: 'Validate drag interactions',
      quest_id: 3,
      completed: false,
      position: 2,
    },
    {
      id: 8,
      title: 'Audit service boundaries',
      quest_id: 4,
      completed: false,
      position: 0,
    },
  ],
  tags: [
    {
      id: 1,
      title: 'Focus',
      level: 8,
      exp_current: 18,
      exp_needed: 60,
      time_spent: 120,
      created_at: '2026-04-01',
      position: 0,
    },
    {
      id: 2,
      title: 'Design',
      level: 16,
      exp_current: 42,
      exp_needed: 100,
      time_spent: 420,
      created_at: '2026-04-01',
      position: 1,
    },
    {
      id: 3,
      title: 'Writing',
      level: 32,
      exp_current: 96,
      exp_needed: 180,
      time_spent: 900,
      created_at: '2026-04-01',
      position: 2,
    },
    {
      id: 4,
      title: 'Frontend',
      level: 52,
      exp_current: 160,
      exp_needed: 260,
      time_spent: 1640,
      created_at: '2026-04-01',
      position: 3,
    },
    {
      id: 5,
      title: 'Systems',
      level: 70,
      exp_current: 250,
      exp_needed: 360,
      time_spent: 2840,
      created_at: '2026-04-01',
      position: 4,
    },
    {
      id: 6,
      title: 'Architecture',
      level: 78,
      exp_current: 410,
      exp_needed: 520,
      time_spent: 5200,
      created_at: '2026-04-01',
      position: 5,
    },
  ],
  rewards: [
    {
      id: 1,
      title: 'Coffee Break',
      cost: 15,
      repeatable: true,
      position: 0,
    },
    {
      id: 2,
      title: 'Buy New Plugin',
      cost: 45,
      repeatable: false,
      position: 1,
    },
    {
      id: 3,
      title: 'Order Favorite Dinner',
      cost: 90,
      repeatable: true,
      position: 2,
    },
    {
      id: 4,
      title: 'Weekend Day Off',
      cost: 160,
      repeatable: false,
      position: 3,
    },
  ],
  questlines_done: [
    {
      id: 1,
      name: 'Quick Refactor Pass',
      created_at: '2026-03-18',
      time_spent: 520,
      status: true,
    },
    {
      id: 2,
      name: 'Experimental Research Spike',
      created_at: '2026-03-24',
      time_spent: 310,
      status: false,
    },
  ],
}

export default defaultData
